import type { Metadata } from "next";
import ".././globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import BlackFridayBanner from "@/components/BlackFridayBanner";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode   } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { LanguageProvider } from "@/lib/languageContext";



export const metadata: Metadata = {
  title: "Kiil Interior Designs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
    <html lang="en">
      <body>
        <LanguageProvider>
          {((await draftMode()).isEnabled &&(
            <>
            <DisableDraftMode/>
            <VisualEditing/>
            </>
          ))}

          <main>  
            <Header/>
            <BlackFridayBanner/>
            {children}</main>
            <SanityLive/> {/*it is a sanity live component//dont forget this else  live update wont work*/}
        </LanguageProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
